11 add features matrix class part 2
CS1103/proyecto-final---te02---202301-pf0220231-grupo1-sub-1 pull request #13
Opened 2023-05-21 23:43 UTC by jonyyy1

2023-05-22 21:55 UTC, RogerHuauya commented on Google_tests/matrix/test_matrix.hpp
> +}
Los test generalmente no tienen .hpp o h, hacer los test encapsulados en una funcion si no se va a testear una funcion directamente de una libreria

2023-05-23 00:42 UTC, gabrielromerod commented on Google_tests/matrix/test_matrix.hpp
> +}
confirmo :+1:

2023-05-23 04:08 UTC, RogerHuauya commented on Google_tests/matrix/test_matrix.cpp
> +    EXPECT_EQ(m1(1,1),5);
dont be pendex, test values that are outside of semidiagonal

2023-05-23 04:09 UTC, RogerHuauya commented on Google_tests/matrix/test_matrix.cpp
> +    EXPECT_EQ(m2(1,1), 5.0);
same here

2023-05-23 04:10 UTC, RogerHuauya requested changes
change test cases for transpose, evaluate that dimensions are transposed

2023-05-23 04:57 UTC, RogerHuauya commented on Google_tests/matrix/test_matrix.cpp
> +    EXPECT_EQ(m1.shape(), std::make_pair(3,2));
unit test for shape missing
m1(5, 1)
expect m1.shape(), makepair(5,1)

2023-05-23 05:19 UTC, RogerHuauya approved these changes
Lgtm

2023-05-23 05:20 UTC, merged